# Generated by Django 6.0.2 on 2026-03-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_bmi_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian'), ('Vegan', 'Vegan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_dislikes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
