# Generated by Django 6.0.2 on 2026-03-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('Lose weight', 'Lose weight'), ('Maintain weight', 'Maintain weight'), ('Gain weight', 'Gain weight'), ('Gain muscle', 'Gain muscle')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
