# Generated by Django 6.0.2 on 2026-03-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_cholesterol_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meals_per_day',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
