# Generated by Django 6.0.2 on 2026-03-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_meals_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='todays_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='todays_steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='todays_water_intake',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
