# Generated by Django 6.0.2 on 2026-03-04 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_manualstepslog_dailysteps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailysteps',
            name='unique_user_daily_steps',
        ),
        migrations.AlterUniqueTogether(
            name='dailysteps',
            unique_together={('user', 'date')},
        ),
    ]
