# Generated by Django 6.0.2 on 2026-03-06 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_fooditem_meallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meallog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'date'], name='user_meallo_user_id_e58eaf_idx'),
        ),
    ]
