# Generated by Django 6.0.2 on 2026-03-07 04:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_mealtemplate_dailymealplan_dailymealentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_unit', models.FloatField()),
                ('protein_per_unit', models.FloatField()),
                ('carbs_per_unit', models.FloatField()),
                ('fats_per_unit', models.FloatField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='100g', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='user_foodlo_user_id_3db659_idx')],
            },
        ),
    ]
