# Generated by Django 6.0.2 on 2026-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_sleepschedule_sleeplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('cook_time', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.JSONField(default=list)),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
