import requests
import json

BASE_URL = "http://127.0.0.1:8000/api"
EMAIL = "test@example.com"
PASSWORD = "Password@123"

def test_ai_meal_plan():
    # 1. Login
    login_url = f"{BASE_URL}/login/"
    login_data = {"email": EMAIL, "password": PASSWORD}
    response = requests.post(login_url, json=login_data)
    if response.status_code != 200:
        print(f"Login failed: {response.text}")
        return
    token = response.json().get("token")
    headers = {"Authorization": f"Token {token}", "Content-Type": "application/json"}
    print("Logged in successfully.")

    # 2. Update Profile to ensure we have BMI and Goal data
    profile_url = f"{BASE_URL}/personal-details/"
    profile_data = {
        "full_name": "AI Test User",
        "age": 30,
        "gender": "Male",
        "height": 180,
        "weight": 85,  # Slightly overweight, BMI ~26.2
        "goal": "Lose weight",
        "diet_type": "Vegetarian",
        "food_allergies": "peanuts"
    }
    requests.post(profile_url, json=profile_data, headers=headers)
    print("Profile updated with 'Lose weight' goal and 'peanuts' allergy.")

    # 3. Generate AI Meal Plan
    today_url = f"{BASE_URL}/meal-plan/today/"
    print("\n--- Generating AI Meal Plan ---")
    res1 = requests.post(today_url, headers=headers) # POST to refresh/generate
    print(f"Status: {res1.status_code}")
    plan = res1.json()
    print(json.dumps(plan, indent=2))
    
    meals = plan.get("meals", [])
    if len(meals) == 4:
        print("Success: 4 meals generated by AI.")
        
        # Check for allergy (Peanuts)
        all_text = " ".join([m["title"] for m in meals]).lower()
        if "peanut" in all_text:
            print("Error: AI selected a meal with peanuts!")
        else:
            print("Success: No peanut-containing meals selected.")
            
        # Check if calories are reasonable for 'Lose weight'
        total_cal = sum(m["calories"] for m in meals)
        print(f"Total Calories: {total_cal} (Target: {plan.get('targetCalories')})")
    else:
        print(f"Error: Expected 4 meals, got {len(meals)}")

    # 4. Test Goal: Muscle Gain
    print("\n--- Switching Goal to 'Gain muscle' ---")
    profile_data["goal"] = "Gain muscle"
    requests.post(profile_url, json=profile_data, headers=headers)
    
    res2 = requests.post(today_url, headers=headers)
    plan2 = res2.json()
    total_cal2 = sum(m["calories"] for m in plan2.get("meals", []))
    print(f"Muscle Gain Total Calories: {total_cal2} (Target: {plan2.get('targetCalories')})")
    
    if total_cal2 > total_cal:
        print("Success: Muscle gain plan has more calories than weight loss plan.")
    else:
        print("Note: Calorie difference not significant or pool limited.")

if __name__ == "__main__":
    test_ai_meal_plan()
